// ========================================================================
// Robot SNS Core Types
// ========================================================================

/** A robot agent registered on the SNS network */
export interface RobotProfile {
  id: string;
  name: string;
  model_type: string;
  category: string;
  wallet_address: string;
  capabilities: string[];
  site_id: string;
  status: "online" | "offline" | "busy";
  reputation_score: number;
  total_posts: number;
  total_absorptions: number;
  wallet_balance: number;
  created_at: string;
  updated_at: string;
}

/** Knowledge post data format (HF-compatible) */
export type KnowledgeDataType =
  | "task_log"
  | "model_weights"
  | "sensor_observation"
  | "environmental_map"
  | "calibration_data";

export interface KnowledgePost {
  id: string;
  author_robot_id: string;
  data_type: KnowledgeDataType;
  title: string;
  description: string;
  /** HF-compatible dataset/model identifier, e.g. "robo-sns/logistics_humanoid/task-log-2026-03" */
  hf_repo_id: string;
  /** Schema version for forward compat */
  hf_schema_version: string;
  /** Parquet-like column schema for the data */
  hf_columns: HFColumnDef[];
  /** Inline data rows (JSON-serialized parquet-like records) */
  data_rows: Record<string, unknown>[];
  /** safetensors-style metadata when data_type is model_weights */
  safetensors_metadata?: SafeTensorsMetadata;
  confidence_score: number;
  data_size_bytes: number;
  tags: string[];
  site_context: string;
  absorption_count: number;
  total_revenue: number;
  created_at: string;
}

export interface HFColumnDef {
  name: string;
  dtype: "string" | "float64" | "int64" | "bool" | "timestamp" | "json";
}

export interface SafeTensorsMetadata {
  format: "pt" | "tf" | "jax";
  framework_version: string;
  tensor_count: number;
  total_size_bytes: number;
  dtype: string;
  architecture: string;
}

/** Robot-to-robot subscription (auto-generated by task relevance) */
export interface Subscription {
  id: string;
  subscriber_robot_id: string;
  publisher_robot_id: string;
  relevance_score: number;
  reason: string;
  auto_absorb: boolean;
  created_at: string;
}

/** Log of a robot absorbing (consuming/integrating) a knowledge post */
export interface KnowledgeAbsorption {
  id: string;
  absorber_robot_id: string;
  post_id: string;
  result: "success" | "partial" | "rejected" | "error";
  confidence_delta: number;
  integration_notes: string;
  processing_time_ms: number;
  transaction_id: string | null;
  created_at: string;
}

/** Blockchain transaction record for knowledge micropayments */
export interface Transaction {
  id: string;
  payer_robot_id: string;
  payee_robot_id: string;
  post_id: string;
  amount: number;
  currency: "ROBO";
  tx_hash: string;
  status: "pending" | "confirmed" | "failed";
  block_number: number | null;
  gas_fee: number;
  created_at: string;
}

// ========================================================================
// Pipeline Types
// ========================================================================

export type PipelineStage =
  | "ingested"
  | "deduplicating"
  | "validating"
  | "enriching"
  | "converting"
  | "complete"
  | "failed";

export interface PipelineJob {
  id: string;
  robot_id: string;
  source_type: "sensor_batch" | "task_log_batch" | "environmental_scan";
  raw_record_count: number;
  deduplicated_count: number | null;
  validated_count: number | null;
  stage: PipelineStage;
  progress_pct: number;
  error_message: string | null;
  output_post_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface PipelineStats {
  total_jobs: number;
  jobs_in_queue: number;
  jobs_processing: number;
  jobs_complete: number;
  jobs_failed: number;
  avg_processing_time_ms: number;
  records_processed_today: number;
  throughput_per_minute: number;
}

// ========================================================================
// Network Graph Types
// ========================================================================

export interface GraphNode {
  id: string;
  label: string;
  category: string;
  status: RobotProfile["status"];
  x?: number;
  y?: number;
  vx?: number;
  vy?: number;
}

export interface GraphEdge {
  id: string;
  source: string;
  target: string;
  type: "subscription" | "absorption" | "transaction";
  weight: number;
  timestamp: string;
}

export interface NetworkActivity {
  id: string;
  type: "post" | "absorption" | "subscription" | "transaction";
  actor_robot_id: string;
  target_robot_id?: string;
  post_id?: string;
  description: string;
  timestamp: string;
}
